# Generated by Django 5.2.1 on 2025-06-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('professor', 'Professor'), ('assistant', 'Assistant'), ('admin', 'Administrator')], max_length=20)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
